apiVersion: "operators.coreos.com/v1"
kind: "CatalogSource"
metadata:
  name: "community-operators"
  namespace: "openshift-marketplace"
spec:
  sourceType: grpc
  image: quay.io/operator-framework/upstream-community-operators:latest
  displayName: "Community Operators"
  publisher: "Red Hat"
  updateStrategy:
    registryPoll:
      interval: 45m
